version: '3.1'
services: 
  postgres:
    restart: always
    image: postgres
    environment: 
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: 'mobileApp'      
    ports: 
      - '5432:5432'